spring:
  datasource:
    url: jdbc:mariadb://115.85.183.199:3306/forten
    username: root
    password:  Qurd%1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    #defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 60919202b9e2848ab48e3044a35f36cc
            clientSecret: ohlUG3DxCEpIu6KM74LzsTH0ZOT8FC9b
#          naver:
#            clientId: fasdf
#            clientSecret: fasdf
#          google:
#            clientId: asdf
#            clientSecret: asdf

        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
#          google:
#            authorizationUri:
#            tokenUri:
#            userInfoUri:
#            userNameAttribute:
#            jwkSetUri:
#          naver:
#            authorizationUri:
#            tokenUri:
#            userInfoUri:
#            userNameAttribute:
#            jwkSetUri:

#  sql:
#    init:
#      mode: always

