spring:
  datasource:
    url: jdbc:mariadb://115.85.183.199:3306/forten
    username: root
    password:  Qurd%1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    #defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 18bc21e0097da6f8542b7530cda0c3ab
            client-secret: ohlUG3DxCEpIu6KM74LzsTH0ZOT8FC9b
            clientName: Kakao
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - account_email
          naver:
            clientId: Lar_nTbtA9zrNrb6_2h0
            clientSecret: 7hysxB2IO6
            clientName: Naver
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - email
          google:
            clientId: 26499517277-vtvp69v0p4rceqkq0qrkeb1jq7u3d9iu.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email

        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
jwt:
  secret: "sadfsadfsadfsadfsdafsadfasdfasfsadfsdafsdafsaffd"
#  sql:
#    init:
#      mode: always

